language: swift
osx_image: xcode11.3

xcode_project: UICircularProgressRing.xcodeproj
xcode_scheme: UICircularProgressRing
xcode_destination: platform=iOS Simulator,OS=10,name=iPhone 7

sudo: enabled

install:
  - ./.travis/install.sh

script:
  - ./.travis/test.sh
  - swiftlint --config src/.swiftlint.yml
